# Lab 1a. Arrays
Probability and Statistics, Spring 2017    
Chanh Nguyen 1504202   
Helsinki Metropolia University of Applied Sciences

Book: Johansson. (2015). [Numerical Python: A Practical Techniques Approach For Industry.](https://metropolia.finna.fi/Record/nelli15.3710000000486209)

## Chapter 2. Vectors, Matrices and Multidimensional Arrays

###### Import numerical python library and refer it as np.

In [149]:
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


###### Create a numerical array having the values: `1, 3, 3, 4, 2, 2, 5, 6, 9'

In [150]:
x = array([1, 3, 3, 4, 2, 2, 5, 6, 7])
x

array([1, 3, 3, 4, 2, 2, 5, 6, 7])

###### Find the dimensions, shape, size, data type and number of bytes in the array.

In [151]:
print('The dimensions is: '+str(x.ndim))
print('The shape is: '+str(x.shape))
print('The size is: '+str(x.size))
print('The data type is: '+str(x.dtype))
print('The number of bytes: '+str(x.nbytes))

The dimensions is: 1
The shape is: (9,)
The size is: 9
The data type is: int32
The number of bytes: 36


###### Create an array of of shape (100,1) filled with 

a) zeros,    
b) ones,    
c) value of 3.14.   

In [152]:
a = zeros((100,))
print('a) Array of shape (100,1) filled with zeros:\n'+str(a)+'\n')
b = empty(100)
b.fill(1)
print('b) Array of shape (100,1) filled with ones:\n'+str(b)+'\n')
c = zeros((100,))
c.fill(3.14)
print('c) Array of shape (100,1) filled with value of 3.14:\n'+str(c)+'\n')

a) Array of shape (100,1) filled with zeros:
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]

b) Array of shape (100,1) filled with ones:
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]

c) Array of shape (100,1) filled with value of 3.14:
[ 3.14  3.14  3.14  3.14  3.14  3.14  3.14

###### Create an array having numbers from 1 to 100.

In [153]:
d = arange(1,101,1)
d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

###### Create an array having number from 1.0 to 3.0 with step size of 0.1

In [154]:
e = arange(1.,3.1,0.1)
e

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ])

###### Create an array having 10 evenly spaced value between 1.0 and 7.2.

In [155]:
f = linspace(1.,7.2,10)
f

array([ 1.        ,  1.68888889,  2.37777778,  3.06666667,  3.75555556,
        4.44444444,  5.13333333,  5.82222222,  6.51111111,  7.2       ])

###### What is the value of the 5th element in the array created in previous exercise?

In [88]:
f[4]

3.7555555555555555

###### Select the elements from 5 to 7 from the array.

In [91]:
f[5:8]

array([ 4.44444444,  5.13333333,  5.82222222])

###### Select two last elements from the array.

In [94]:
f[f.size-2:]

array([ 6.51111111,  7.2       ])

###### Create a 10 x 10 array filled with zeros.

In [156]:
g = zeros((10,10))
g

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

###### Replace the values with values from 1 to 100 in the previous array.

In [173]:
g = arange(1,101,1).reshape(10,10)
g

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

###### Clear (change the values to zero) the 3rd row in the array.

In [174]:
g[2]=0
g

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

###### Clear the 7th column in the array

In [175]:
for i in range(10): g[i][6]=0
g

array([[  1,   2,   3,   4,   5,   6,   0,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,   0,  18,  19,  20],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 31,  32,  33,  34,  35,  36,   0,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,   0,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,   0,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,   0,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,   0,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,   0,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,   0,  98,  99, 100]])

###### Create and array having the values `1, 3, 3, 5, 4, 2, 7, 9`

In [201]:
h = array([1,3,3,5,4,2,7,9])
h

array([1, 3, 3, 5, 4, 2, 7, 9])

###### Find all values in the array being greater than 4.

In [202]:
h[h>4]

array([5, 7, 9])

###### Change all the value being less or equal to 3 to value `nan`

In [205]:
h = where(h<=3, nan, h)
h

array([ nan,  nan,  nan,   5.,   4.,  nan,   7.,   9.])

###### Create two arrays, the first having values `1, 3, 5` and the second `2, 4, 6`

In [245]:
i = array([1,3,5])
j = array([2,4,6])
i,j

(array([1, 3, 5]), array([2, 4, 6]))

###### Combine the arrays horizontally (e.g. make a one long row).

In [246]:
append(i,j)

array([1, 3, 5, 2, 4, 6])

###### Combine the arrays vertically (e.g. make an array having two rows).

In [256]:
vstack((i,j))

array([[1, 3, 5],
       [2, 4, 6]])

###### Combine the arrays and sort them in ascending order.

In [255]:
sort(append(i,j))

array([1, 2, 3, 4, 5, 6])

###### Create an array having numbers from 0.0 to 1.0 with stepsize 0.05.

In [261]:
k = arange(0,1.05,.05)
k

array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ])

###### Calculate the sine of each element in the previous exercise.

In [262]:
sin(k)

array([ 0.        ,  0.04997917,  0.09983342,  0.14943813,  0.19866933,
        0.24740396,  0.29552021,  0.34289781,  0.38941834,  0.43496553,
        0.47942554,  0.52268723,  0.56464247,  0.60518641,  0.64421769,
        0.68163876,  0.71735609,  0.75128041,  0.78332691,  0.8134155 ,
        0.84147098])

###### Calculate the square root of each element.

In [263]:
k**2

array([ 0.    ,  0.0025,  0.01  ,  0.0225,  0.04  ,  0.0625,  0.09  ,
        0.1225,  0.16  ,  0.2025,  0.25  ,  0.3025,  0.36  ,  0.4225,
        0.49  ,  0.5625,  0.64  ,  0.7225,  0.81  ,  0.9025,  1.    ])

###### Calculate $y=3x^2 - 5x + 3$, when x varies from -5 to 5 with stepsize of 0.5

In [264]:
x = arange(-5,5,.5)
y = 3*x**2-5*x+3
y

array([ 103.  ,   86.25,   71.  ,   57.25,   45.  ,   34.25,   25.  ,
         17.25,   11.  ,    6.25,    3.  ,    1.25,    1.  ,    2.25,
          5.  ,    9.25,   15.  ,   22.25,   31.  ,   41.25])

###### Convert the values of the previous exercise to the closest integer.

In [266]:
around(y)

array([ 103.,   86.,   71.,   57.,   45.,   34.,   25.,   17.,   11.,
          6.,    3.,    1.,    1.,    2.,    5.,    9.,   15.,   22.,
         31.,   41.])

###### Create a numerical array having the values: `1, 3, 3, 4, 2, 2, 5, 6, 9'

In [269]:
l = array([1,3,3,4,2,2,5,6,9])
l

array([1, 3, 3, 4, 2, 2, 5, 6, 9])

###### Calculate the mean and standard deviation of the array

In [274]:
mean(l), std(l)

(3.8888888888888888, 2.3306863292670035)

###### Find the minimum, the maximum, and the median values of the array.

In [275]:
min(l), max(l), median(l)

(1, 9, 3.0)

###### Find the index for the minimum value.

In [283]:
where(l == min(l))

(array([0], dtype=int64),)

###### Find the index for the maximum value.

In [284]:
where(l == max(l))

(array([8], dtype=int64),)

##### Sum all elements together.

In [285]:
sum(l)

35

###### Check if all elements are less than 9.

In [288]:
where(l >= 9)

(array([8], dtype=int64),)

###### Check if any of the elements is equal to 5

In [289]:
where(l == 5)

(array([6], dtype=int64),)

###### Sort the values in array in descending order (from maximum to minimum).

In [293]:
sort(l)[::-1]

array([9, 6, 5, 4, 3, 3, 2, 2, 1])

Multiply the following matrices using the matrix multiplication (dot-product).   
$ A= \begin{bmatrix}
1 & 2 \\
5 & 3\\
\end{bmatrix}$ and 
$x = \begin{bmatrix}
-2 \\ 
3\\ 
\end{bmatrix}$

In [301]:
A = array([[1,3],[5,3]])
x = array([-2,3])
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

###### Import from `numpy.linalg` module the functions `inv` and `solve`

In [302]:
from numpy.linalg import inv, solve

Find the inverse of matrix A.

In [304]:
inv(A)

array([[-0.25      ,  0.25      ],
       [ 0.41666667, -0.08333333]])

Using `solve` function solve the system of equations 
$\begin{bmatrix}1 & 2 \\ 5 & 3\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 9 \\ 31 \end{bmatrix}$

In [305]:
b = array([9, 31])
solve(A, b)

array([ 5.5       ,  1.16666667])

Solve the $Ax=b$, where $A = \begin{bmatrix} 4 & 8 & 20 \\ 8 & 13 & 16 \\ 20 & 16 & -91\end{bmatrix}$ and $b = \begin{bmatrix}24 \\ 18 \\ -199 \end{bmatrix}$.

In [308]:
A = array([4,8,20,8,13,16,20,16,-91]).reshape(3,3)
b = array([24,18,-199])
solve(A,b)

array([-883.,  642.,  -79.])