# Assignment 5 - Applications
Introduction to Numerical Problem Solving, Spring 2017   
Chanh Nguyen, 1504202   
Helsinki Metropolia University of Applied Sciences

In [68]:
# Initial import statements
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *

from scipy.linalg import *

import math

### Exercise 1

In [69]:
# The mass
m_1,m_2,m_3,m_4 = [10.,4.,5.,6.]

A = array([[m_1,1,0,0],
           [m_2,-1,1,0],
           [m_3,0,-1,1],
           [m_4,0,0,-1]])
# Left side of the equations
A

array([[ 10.,   1.,   0.,   0.],
       [  4.,  -1.,   1.,   0.],
       [  5.,   0.,  -1.,   1.],
       [  6.,   0.,   0.,  -1.]])

In [70]:
# Convert theta to radian, value g, mu
theta = radians(45)
g = 9.81
mu_1,mu_2,mu_3 = [.25,.3,.2]

b = array([m_1*g*(sin(theta)-mu_1*cos(theta))
          ,m_2*g*(sin(theta)-mu_2*cos(theta))
          ,m_3*g*(sin(theta)-mu_3*cos(theta))
          ,-m_4*g])
# Right side of the equations
b

array([ 52.02538143,  19.42280907,  27.74687009, -58.86      ])

In [71]:
# Solve for x
x = solve(A,b)
print("a = " + str(x[0]))
print("T1 = " + str(x[1]))
print("T2 = " + str(x[2]))
print("T3 = " + str(x[3]))

a = 1.61340242341
T1 = 35.8913571917
T2 = 48.8605565637
T3 = 68.5404145404


In [73]:
# Solve the degree to make a = 0
eps = 10e-2
result = 45
for thetaDegree in range(45, 0, -1):
    thetaRadian = radians(thetaDegree)
    b = array([m_1*g*(sin(thetaRadian)-mu_1*cos(thetaRadian))
              ,m_2*g*(sin(thetaRadian)-mu_2*cos(thetaRadian))
              ,m_3*g*(sin(thetaRadian)-mu_3*cos(thetaRadian))
              ,-m_4*g])
    x = solve(A,b)
    if x[0] < eps:
        result = thetaDegree
        break
print(x)
print("The degree to make a = 0 is: "+str(result)+" degree")

[  3.24279236e-02   3.08624210e+01   4.15435191e+01   5.90545675e+01]
The degree to make a = 0 is: 32 degree
