# Exercise 05 - Solutions
    Introduction to Numerical Problem Solving, Spring 2017
    21.2.2017, Olli Kortelainen
    Helsinki Metropolia University of Applied Sciences

### Home assigment 05 - LU Decomposition, Inverse Matrix, and Gauss-Seidel method

In [1]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *
from scipy.misc import factorial
from numpy.linalg import *
from scipy.linalg import lu,solve,inv,det,lu_factor,lu_solve
from pprint import pprint


### LUdecomp method

In [7]:
def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if [a,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a

### LUsolve method

In [8]:
def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - dot(a[k,0:k],b[0:k])
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

## Gauss-Seidel method
    Taken from PDF (or book).
    Method was modified it to work in my code.

In [30]:
def gaussSeidel(A, b, x0, w):
    n = len(x0)
    x = x0
    for k in range(10):
        for i in range(n):
            s = 0
            for j in range(n):
                if j != i:
                    s = s + A[i,j]*x[j]
            x[i] = w/A[i,i]*(b[i] - s)+((1.0-w)*x[i])
    return x

## Problem 3
    Write a Python program that solves Ax = b using LU decomposition.
    Use the functions LUdecomp and LUsolve.
### Solution
    Using LUdecomp and LUsolve, that are taken from the PDF(or book) we got during class.


In [18]:
A = array([[1.0,  4,  1],
           [1,  6, -1],
           [2, -1,  2]])

b = array([7, 13, 5])

C = A.copy()

LUdecomp(A)
x = LUsolve(A,b)
print(x)

# Testing that my solution is correct.
dot(C,x)




[ 5  1 -2]


array([  7.,  13.,   5.])

## Problem 6
    Invert the following matrices with any method
### Solution
    Simply using inv()-method to do the inverting. 
    Array A can be inverted but array B cannot be. 

In [27]:
A = array([[ 5,  -3,  -1,  0],
           [-2,   1,   1,  1],
           [ 3,  -5,   1,  2],
           [ 0,   8,  -4, -3]])

B = array([[  1,  3,  -9,  6,  4],
           [  2, -1,   6,  7,  1],
           [  3,  2,  -3, 15,  5],
           [  8, -1,   1,  4,  2],
           [ 11,  1,  -2, 18,  7]])

invA = inv(A)
invB = inv(B) 

pprint(around(invA))
pprint(around(invB)) 

resultA = around(dot(A, dot(A, invA)), 8)
#proof of inv() working
print(resultA)

array([[ 1.,  1., -1., -0.],
       [ 1.,  1., -1., -0.],
       [ 2.,  2., -2., -1.],
       [-1., -0.,  1.,  1.]])
array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -0.00000000e+00,  -0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,  -0.00000000e+00],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])
[[ 5. -3. -1.  0.]
 [-2.  1.  1.  1.]
 [ 3. -5.  1.  2.]
 [ 0.  8. -4. -3.]]


## Problem 9
    Use the Gauss-Seidel with relaxation to solve Ax = b
    Take xi = bi/Aii as the starting vector, and use w = 1.1 for the relaxation factor.
    
### Solution
    Using gaussSeidel() method above.

In [38]:
A = array([[ 4.0, -1,  0,  0],
           [-1,  4, -1,  0],
           [ 0, -1,  4, -1],
           [ 0,  0, -1,  3]])

b = array([15.0, 10, 10, 10])

x0 = array([1.0,1.0,1.0,1.0])

result = gaussSeidelRelaxation(A,b,x0,1.1)
print(result)

around(dot(A, result))

[ 4.99999999  5.          5.          5.        ]


array([ 15.,  10.,  10.,  10.])