# Assignment 05
## LU Decomposition, Matrix Inversion and Gauss-Seidel
15.2.2017, William Smith

In [2]:
#initial import statements
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *

## Problem 1
Given LU decomposition A = LU, determine A

I believe the solution is dot(LU) = A

In [3]:
from scipy.linalg import lu, solve
from pprint import pprint

L = array([ [1,0,0],[1,1,0],[1, 5.0/3.0, 1] ])
U = array([ [1,2,4],[0,3,21],[0,0,0] ])

A = dot(L,U)
print(A)

[[  1.   2.   4.]
 [  1.   5.  25.]
 [  1.   7.  39.]]


## Problem 2
Use the results of LU decomposition to solve Ax = b, where b^T = [1,-1,2]

I believe the solution for x is to use lu() function with the given LU decomposition for A and b^T

In [4]:
L = array([ [1,0,0],[3/2,1,0],[1/2,11/13,1] ])
U = array([ [2,-3,-1],[0,13/2,-7/2],[0,0,32/13] ])
b = array([1,-1,2])

A = dot(L,U)

y = solve(L, b)
x = solve(U,y)

print("x:")
pprint(x)

solve(A,b)

x:
array([ 1.84375,  0.40625,  1.46875])


array([ 1.84375,  0.40625,  1.46875])

## Problem 3
Write a program that solves Ax = b using LU decomposition.
Use the functions LUdecomp and LUsolve.

In [5]:
#be careful with integer division
#for this reason I made the first elements in A and B reals

A = array([ [1.0,4,1], [1,6,-1],[2,-1,2] ])
b = array([7.0,13,5])
C = A.copy()

#the LUdecomp is coming from book example
def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if [a,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a

#the LUsolve is coming from book example
def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - dot(a[k,0:k],b[0:k])
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

LUdecomp(A)
x = LUsolve(A,b)

#checking answer
A = array([ [1,4,1], [1,6,-1],[2,-1,2] ])
b = array([7,13,5])
dot(A,x)

array([  7.,  13.,   5.])

## Problem 4
Write a function that inverts a matrix. Test the function by inverting.

My solution is to use the inv() function and then compare results with written function.

In [6]:
from scipy.linalg import inv, lu_factor, lu_solve

A = array([0.6, -0.4, 1.0, -0.3, 0.2, 0.5, 0.6, -1.0, 0.5]).reshape(3,3)
aInv = inv(A)

def inverse(a):
    n = len(a[0])
    aInv = np.identity(n)
    a = lu_factor(a)
    for i in range(n):
        aInv[:,i] = lu_solve(a,aInv[:,i])
    return aInv

#results match up
print(inverse(A))
print(inv(A))

#this is funny because the first elements do not match, must be rounding error
inverse(A)==inv(A) 

[[ 1.66666667 -2.22222222 -1.11111111]
 [ 1.25       -0.83333333 -1.66666667]
 [ 0.5         1.          0.        ]]
[[ 1.66666667 -2.22222222 -1.11111111]
 [ 1.25       -0.83333333 -1.66666667]
 [ 0.5         1.          0.        ]]


array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Problem 5
Invert the triangular matrices. What do you observe?

In [7]:
A = array([2,4,3,0,6,5,0,0,2]).reshape(3,3)
B = array([2,0,0,3,4,0,4,5,6]).reshape(3,3)

Pa,La,Ua = lu(A)
Pb,Lb,Ub = lu(B)

print("Here are the inverses for LU of A matrix")
LaInv = inv(La)
print(LaInv)
UaInv = inv(Ua)
print(UaInv)

print("\nHere are the inverses for LU of B matrix")
LbInv = inv(Lb)
print(LbInv)

UbInv = inv(Ub)
print(UbInv)

Here are the inverses for LU of A matrix
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
[[ 0.5        -0.33333333  0.08333333]
 [ 0.          0.16666667 -0.41666667]
 [ 0.          0.          0.5       ]]

Here are the inverses for LU of B matrix
[[ 1.  -0.  -0. ]
 [-0.5  1.  -0. ]
 [-0.8  0.1  1. ]]
[[ 0.25        0.5         0.        ]
 [ 0.         -0.4         0.25      ]
 [ 0.          0.         -0.20833333]]


Did not observer anything special. But I think I was supposed to compare the inverse of A and B not there LU decompositions.

In [13]:
print(around(inv(A),1))
around(inv(B),1)

[[-0.   0.1 -0. ]
 [ 0.   0.1  0.1]
 [ 0.1 -0.  -0.1]]


array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.00000000e-01,  -3.00000000e-01,   7.00000000e-01,
          3.00000000e-01,  -3.00000000e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])

Their lower and upper triangles in inversion are kinda flipped or mirrored

## Problem 6
Invert matrices using any method and comment on reliability

In [9]:
A = array([5,-3,-1,0,-2,1,1,1,3,-5,1,2,0,8,-4,-3]).reshape(4,4)
B = array([1,3,-9,6,4,2,-1,6,7,1,3,2,-3,15,5,8,-1,1,4,2,\
           11,1,-2,18,7]).reshape(5,5)

aInv = inv(A)
bInv = inv(B)

resultA = around(dot(A, dot(A, aInv)), 8)
#result of using inv() worked fine
print(resultA)



[[ 5. -3. -1.  0.]
 [-2.  1.  1.  1.]
 [ 3. -5.  1.  2.]
 [ 0.  8. -4. -3.]]


## Gause-Seidel method

In [10]:
def gaussSeidel(A, b, x0):
    n = len(x0)
    x = x0
    for k in range(10):
        for i in range(n):
            s = 0
            for j in range(n):
                if j != i:
                    s = s + A[i,j]*x[j]
            x[i] = 1/A[i,i]*(b[i] - s)
    return x

## Problem 8
Use Gauss-Seidel method to solve the problem

In [11]:
A = array([-2.0,5,9,7,1,1,-3,7,-1]).reshape(3,3)
b = array([1.0,6,-26])

#make sure the highest values go in diagonal in matrices
A1 = array([7,1,1,-3,7,-1,-2,5,9]).reshape(3,3)
b1 = array([6,-26,1.])

x0 = array([1.0,1.0,1.0])
x = gaussSeidel(A1, b1, x0)
x

array([ 1., -3.,  2.])

In [14]:
dot(A1, x)

array([  6., -26.,   1.])

## Problem 9
Use the Gauss-Seidel with relaxation to solve Ax = b with an over-relaxation factor of 1.1

In [22]:
A = array([4.0,-1,0,0, -1,4,-1,0, 0,-1,4,-1, 0,0,-1,3]).reshape(4,4)
b = array([15.0,10,10,10])
x0 = array([1.0,1.0,1.0,1.0])

My way forward is to take existing Gauss-Seidel function and modify it to use over-relaxation.

In [26]:
def gaussSeidelRelaxation(A, b, x0, w):
    n = len(x0)
    x = x0
    for k in range(10):
        for i in range(n):
            s = 0
            for j in range(n):
                if j != i:
                    s = s + A[i,j]*x[j]
            x[i] = w/A[i,i]*(b[i] - s)+((1.0-w)*x[i])
    return x

In [28]:
result = gaussSeidelRelaxation(A,b,x0,1.1)
result

array([ 5.,  5.,  5.,  5.])

I don't know if I trust the result. At first attempt, the first element was 4.99, so then I changed some integers to floats. Let's now test with dot product.

In [29]:
dot(A, result)

array([ 15.,  10.,  10.,  10.])

Woo hoo! It worked.