# Assignment 5
LU Decomposition, Inverse Matrix, and Gauss-Seidel method <br>
Ali Çelik<br>
26.02.2017

In [1]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *
from scipy.linalg import lu,solve
from pprint import pprint
from scipy.linalg import lu_factor, lu_solve, inv

## Problem 3

Solve Ax=b by LU decomposition, use la_factor and la_solve:

<b> Solution: </b>

In [2]:
A = array([1,4,1,1,6,-1,2,-1,2]).reshape(3,3)
b = array([7,13,5])
lu_solve(lu_factor(A),b)

array([ 5.,  1., -2.])

Basically we just used the default functions from scipy.linalg as we asked to do so.

## Problem 6

Invert the following matrices by any method:

<b> Solution: </b>

In [3]:
A = array([5,3,-1,0,-2,1,1,1,3,-5,1,2,0,8,-4,-3]).reshape(4,4)
B = array([1,3,-9,6,4,2,-1,6,7,1,3,2,-3,15,5,8,-1,1,4,2,11,1,-2,18,7]).reshape(5,5)
print('A:')
pprint(A)
print('B:')
pprint(B)


A:
array([[ 5,  3, -1,  0],
       [-2,  1,  1,  1],
       [ 3, -5,  1,  2],
       [ 0,  8, -4, -3]])
B:
array([[ 1,  3, -9,  6,  4],
       [ 2, -1,  6,  7,  1],
       [ 3,  2, -3, 15,  5],
       [ 8, -1,  1,  4,  2],
       [11,  1, -2, 18,  7]])


So, let's use numpy.linalg.inv first;

In [4]:
print('A inverse with inv(A):')
pprint(inv(A))
print('B inverse with inv(B):')
pprint(inv(B))

A inverse with inv(A):
array([[ 0.19148936, -0.14893617, -0.08510638, -0.10638298],
       [ 0.13829787,  0.17021277, -0.11702128, -0.0212766 ],
       [ 0.37234043, -0.23404255, -0.77659574, -0.59574468],
       [-0.12765957,  0.76595745,  0.72340426,  0.40425532]])
B inverse with inv(B):
array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.33333333e-01,  -3.33333333e-01,   6.66666667e-01,
          3.33333333e-01,  -3.33333333e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])


Now let's use the matInv function that we developed in the class;

In [5]:
def matInv(a):
    n = len(a[0])
    aInv = np.identity(n)
    a = lu_factor(a) #We use this instead of the LUdecomp and Lusolve because they don't include pivotting
    for i in range(n):
        aInv[:,i] = lu_solve(a,aInv[:,i])
    return aInv

In [6]:
print('A inverse with matInv(A):')
pprint(matInv(A))
print('B inverse with matInv(B):')
pprint(matInv(B))

A inverse with matInv(A):
array([[ 0.19148936, -0.14893617, -0.08510638, -0.10638298],
       [ 0.13829787,  0.17021277, -0.11702128, -0.0212766 ],
       [ 0.37234043, -0.23404255, -0.77659574, -0.59574468],
       [-0.12765957,  0.76595745,  0.72340426,  0.40425532]])
B inverse with matInv(B):
array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.33333333e-01,  -3.33333333e-01,   6.66666667e-01,
          3.33333333e-01,  -3.33333333e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])


And now let's check the reliability of the results. As we know from our math classes, multiplication of a matrix with its inverse gives us the identity matrix. So, let's see if this will be the case with our inverses as well:

In [7]:
A_inverse = np.linalg.inv(A)
B_inverse = np.linalg.inv(B)
print('Multiplication of A and inv(A):')
pprint(around(dot(A,A_inverse)))
print('Multiplication of B and inv(B):')
pprint(around(dot(B,B_inverse)))

Multiplication of A and inv(A):
array([[ 1.,  0., -0.,  0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
Multiplication of B and inv(B):
array([[-1.,  0., -2.,  0., -2.],
       [ 0.,  1.,  0., -0.,  2.],
       [-2., -0., -0.,  0., -2.],
       [ 0., -1., -1., -2.,  5.],
       [-1.,  0., -3., -2.,  6.]])


And now let's check with our matInv function:

In [8]:
print('Multiplication of A and matInv(A):')
pprint(around(dot(A,matInv(A))))
print('Multiplication of B and matInv(B):')
pprint(around(dot(B,matInv(B))))

Multiplication of A and matInv(A):
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
Multiplication of B and matInv(B):
array([[ 0.,  0., -2.,  0., -2.],
       [ 0.,  1.,  0., -0.,  2.],
       [-0., -0., -0.,  0., -2.],
       [-0., -1., -1., -2.,  5.],
       [-2.,  0., -3., -2.,  6.]])


Conclusion; As we can see from the results matrix inverse function worked fine with the 4x4 matrix A, but there seems to be an issue with the 5x5 matrix B. For different types of matrices, different methods should be considered when taking inverses. 

## Problem 9

Use Gauss-Seidel with relaxation to solve Ax=b, relaxation w=1.1

<b> Solution: </b>

In [9]:
def gaussSeidelWithRelaxation(a, b, x0,w): #w is the relaxation number
    n = len(x0)
    x = x0
    for k in range(10):
        for i in range(n):
            sum_total = 0
            for j in range(n):
                if j != i:
                    sum_total = sum_total + A[i,j]*x[j]
            x[i] = (w/A[i,i]*(b[i] - sum_total)) + (1-w)*x[i]
    return x

In [10]:
A = array([4,-1,0,0,-1,4,-1,0,0,-1,4,-1,0,0,-1,3]).reshape(4,4)
b = array([15,10,10,10])
x0 = array([1.0,1.0,1.0,1.0])
x = gaussSeidelWithRelaxation(A,b,x0,1.1)
x


array([ 4.99999999,  5.        ,  5.        ,  5.        ])

And to see if the result is correct, we can compare it with the solve(A,b):

In [11]:
solve(A,b)

array([ 5.,  5.,  5.,  5.])

As we can see from the solve( ) function, the Gauss-Seidel with relaxation works well.