# Week 5

In [1]:
# Initial import statements
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *

## Problem 3
Write a Python program that solves Ax = b using LU decomposition.
Use the functions lu factor and lu solve from scipy.linalg package

### Solution


In [5]:
from pprint import pprint
from scipy.linalg import lu, solve

A = array([[1, 4, 1],[1,6,-1],[2,-1,2]])
b = array([7, 13, 5])
P, L, U = lu(A)

y = solve(dot(P, L), b)
x = solve(U, y)

print("X:")
pprint(x)

X:
array([ 5.,  1., -2.])


## Problem 6
Invert the following matrices with any method

### Solution

In [13]:
from scipy.linalg import inv
from pprint import pprint

A = ([[ 5,-3,-1, 0],
      [-2, 1, 1, 1],
      [ 3,-5, 1, 2],
      [ 0, 8,-4,-3]])
B = ([[1, 3,-9, 6, 4],
      [2,-1, 6, 7, 1],
      [3, 2,-3,15, 5],
      [8,-1, 1, 4, 2],
      [11,1,-2,18, 7]])

inv(A)
inv(B)

print("A:")
pprint(around(inv(A)))

print("B:")
pprint(inv(B))

A:
array([[ 1.,  1., -1., -0.],
       [ 1.,  1., -1., -0.],
       [ 2.,  2., -2., -1.],
       [-1., -0.,  1.,  1.]])
B:
array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.33333333e-01,  -3.33333333e-01,   6.66666667e-01,
          3.33333333e-01,  -3.33333333e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])


## Problem 9
Use the Gauss-Seidel with relaxation to solve Ax = b

### Solution

In [71]:
A = np.array([[ 4.,-1., 0., 0.],
              [-1., 4.,-1., 0.],
              [ 0.,-1., 4.,-1.],
              [ 0., 0.,-1., 3.]])
b = np.array([15.,10.,10.,10.])

iterations = 1000

w = 1.1
x = np.zeros_like(b)

for z in range(iterations):
    for i in range(A.shape[0]):
        a = 0
        for j in range(A.shape[1]):
            if j != i:
                a = a + A[i,j]*x[j]
            x[i] = (w/A[i,i])*(b[i] - a) + (1 - w)*x[i]
        
print("Solution:")
print(x)
error = np.dot(A, x) - b
print("Error:")
print(error)

Solution:
[ 5.00747101  5.02435668  5.14085529  5.02998524]
Error:
[ 0.00552735 -0.05089956  0.50907922 -0.05089956]
