## Week 04
Chanh Nguyen

In [1]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *

In [2]:
A = array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [3]:
A.T

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.]])

### Problem 1
Find the solution for the given system of equations

In [7]:
from numpy.linalg import solve, inv, det

In [8]:
A = array([[3.0, -0.1, -0.2], [0.1, -7.0, -0.3], [0.3, -0.2, -10.0]])
b = array([7.85, -19.3, 71.4])
x = solve(A, b)
print("x = ", x)

x =  [ 2.2441941   3.09497021 -7.13457358]


### Gaussian elimination

In [64]:
def Gaussian(A, b):
    A = A.copy()
    b = b.copy()
    #rowsA, colsA = shape(A)
    N = len(b)
    x = zeros(N)
    # Step 1. Forward elimination
    for k in range(0, N-1):
        #print("k = ", k)
        for i in range(k+1, N):
            #print("i = ", i)
            factor = A[i, k] / A[k, k]
            #print("factor = ", factor)
            for j in range(N):
                #print("j = ", j)
                A[i, j] -= factor * A[k, j]
            b[i] -= factor * b[k]
            #print("k, i = ", k, i)
            #print("A = \n", A)        
            #print("b = \n", b)        
    # Step 2. Backward substitution
    #x[N-1] = b[N-1] / A[N-1, N-1]
    for i in range(N-1, -1, -1):
        s = b[i]
        for j in range(i+1, N):
            s -= A[i, j] * x[j]
        x[i] = s / A[i, i]
        #print("x = ", x)
    return x

In [66]:
A = array([[3.0, -0.1, -0.2], [0.1, -7.0, -0.3], [0.3, -0.2, -10.0]])
b = array([7.85, -19.3, 71.4])
Gaussian(A, b)
print("A = \n", A)        
print("b = \n", b)
print("x = ", x)

A = 
 [[  3.   -0.1  -0.2]
 [  0.1  -7.   -0.3]
 [  0.3  -0.2 -10. ]]
b = 
 [  7.85 -19.3   71.4 ]
x =  [ 2.2441941   3.09497021 -7.13457358]


In [68]:
A = array([[0.0, 2.0, 3.0], [4.0, 6.0, 7.0], [2.0, 1.0, 6.0]])
b = array([8.0, -3.0, 5.0])
Gaussian(A, b)

C:\Users\Chanh Nguyen\Anaconda3\lib\site-packages\ipykernel\__main__.py:12: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\Chanh Nguyen\Anaconda3\lib\site-packages\ipykernel\__main__.py:16: RuntimeWarning: invalid value encountered in double_scalars
C:\Users\Chanh Nguyen\Anaconda3\lib\site-packages\ipykernel\__main__.py:12: RuntimeWarning: invalid value encountered in double_scalars


array([ nan,  nan,  nan])

In [70]:
A = array([[4.0, 6.0, 7.0], [0.0, 2.0, 3.0], [2.0, 1.0, 6.0]])
b = array([-3.0, 8.0, 5.0])
Gaussian(A, b)

array([-5.43181818,  0.04545455,  2.63636364])

In [74]:
def GaussianPivot(A, b):
    A = A.copy()
    b = b.copy()
    N = len(b)
    x = zeros(N)
    # Step 1. Forward elimination
    for k in range(0, N-1):
        # Pivoting the rows
        r = argmax(abs(A[k:, k])) + k
        
        if r != k:
            temp = A[k, :].copy()
            A[k, :] = A[r, :]
            A[r, :] = temp

            temp = b[k].copy()
            b[k] = b[r]
            b[r] = temp
        
        for i in range(k+1, N):
            factor = A[i, k] / A[k, k]
            for j in range(N):
                A[i, j] -= factor * A[k, j]
            b[i] -= factor * b[k]
        
    # Step 2. Backward substitution
    for i in range(N-1, -1, -1):
        s = b[i]
        for j in range(i+1, N):
            s -= A[i, j] * x[j]
        x[i] = s / A[i, i]

    return x

In [75]:
A = array([[1, 2, 3], [0, 1, 3], [0, -7, 6]])
print(A)

[[ 1  2  3]
 [ 0  1  3]
 [ 0 -7  6]]


In [76]:
A = array([[0.0, 2.0, 3.0], [4.0, 6.0, 7.0], [2.0, 1.0, 6.0]])
b = array([8.0, -3.0, 5.0])
GaussianPivot(A, b)

array([-5.43181818,  0.04545455,  2.63636364])