In [4]:
# Initial import statements
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *

from scipy.linalg import *

import math

In [12]:
r1=5
r2=5
r3=5
r4=10
r5=15
r6=20

A = array([1.,-1,-1,0,0,0,0,1,0,-1,0,0,0,0,0,1,-1,0,0,0,1,0,1,-1,-r1,0,-r3,0,0,-r6,-r1,-r2,0,-r4,-r5,-r6]).reshape(6, 6)
A

array([[  1.,  -1.,  -1.,   0.,   0.,   0.],
       [  0.,   1.,   0.,  -1.,   0.,   0.],
       [  0.,   0.,   0.,   1.,  -1.,   0.],
       [  0.,   0.,   1.,   0.,   1.,  -1.],
       [ -5.,   0.,  -5.,   0.,   0., -20.],
       [ -5.,  -5.,   0., -10., -15., -20.]])

In [19]:
vs=0.2e3
b = array([0,0,0,0,-vs,-vs])
b

array([   0.,    0.,    0.,    0., -200., -200.])

In [20]:
i = solve(A,b)
i

array([ 6.82926829,  0.97560976,  5.85365854,  0.97560976,  0.97560976,
        6.82926829])

In [25]:
A2 = array([1.,0,0,0,0,0,1,-1,0,0,0,0,0,1,-1,0,0,0,0,0,1,-1,0,0,0,0,0,1,-1,0,0,0,0,0,1,-1]).reshape(6, 6)
A2

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.]])

In [26]:
v1 = array([0.,vs,-r1*i[0],-r2*i[1],-r4*i[3],-r3*i[2]])
v = solve(A2,v1)
v

array([   0.        , -200.        , -165.85365854, -160.97560976,
       -151.2195122 , -121.95121951])

In [70]:
H = array([[0,0,0,0,0,0,1,0],
           [1,0,1,1,0,0,0,0],
           [1,0,0,0,0,0,0,0],
           [0,1,0,0,0,0,0,0],
           [0,0,1,1,0,0,1,0],
           [0,0,0,1,1,0,0,1],
           [0,0,0,0,1,0,0,1],
           [0,0,0,0,1,1,1,0]])
H

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0]])

In [71]:
np.fill_diagonal(H,0)
H

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 0]])

In [75]:
H = H/sum(H,0)
print(around(H,3))

[[ 0.     0.     0.     0.     0.     0.     0.333  0.   ]
 [ 0.5    0.     0.5    0.333  0.     0.     0.     0.   ]
 [ 0.5    0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     1.     0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.5    0.333  0.     0.     0.333  0.   ]
 [ 0.     0.     0.     0.333  0.333  0.     0.     0.5  ]
 [ 0.     0.     0.     0.     0.333  0.     0.     0.5  ]
 [ 0.     0.     0.     0.     0.333  1.     0.333  0.   ]]


In [78]:
x = array([1,0,0,0,0,0,0,0])
for n in range(500):
    xnew = dot(H,x)
    err = mean(abs(xnew-x))
    if err < 1e-5:
        break
    x = xnew
print(n)
print(around(x,5))

65
[ 0.06     0.0675   0.03     0.0675   0.0975   0.20251  0.18001  0.29499]


In [111]:
txt = """
0	0	1	1	1	0	1	0	100
0	2147483647	1	0	0	1	0	0	100
0	0	5	1	1	0	0	0	100
0	0	0	7	0	1	0	1	100
0	0	0	1	10e**100	0	0	0	100
0	1	0	0	1	1	0	1	100
0	0	0	1	0	1	0	1	100
0	1	0	1	1	1	1	9	100
0	0	3	1	0	1	0	1	2
"""
H = matrix(txt).reshape(9,9)
H = asarray(H,dtype=float)
fill_diagonal(H,0)
csum = sum(H,0)
for n in range(9):
    if csum[n] == 0:
        H[:,n] = ones(9)
        H[n,n] = 0
        csum[n] = 9-1
H = H/csum
print(around(H,3))

x = zeros(9)
x[0] = 1
for n in range(500):
    xnew = dot(H,x)
    err = mean(abs(xnew-x))
    if err < 1e-5:
        break
    x = xnew
print(n)
print(around(x,5))
# sum(x)

flipud(argsort(x))

[[ 0.     0.     0.2    0.167  0.25   0.     0.5    0.     0.125]
 [ 0.125  0.     0.2    0.     0.     0.2    0.     0.     0.125]
 [ 0.125  0.     0.     0.167  0.25   0.     0.     0.     0.125]
 [ 0.125  0.     0.     0.     0.     0.2    0.     0.25   0.125]
 [ 0.125  0.     0.     0.167  0.     0.     0.     0.     0.125]
 [ 0.125  0.5    0.     0.     0.25   0.     0.     0.25   0.125]
 [ 0.125  0.     0.     0.167  0.     0.2    0.     0.25   0.125]
 [ 0.125  0.5    0.     0.167  0.25   0.2    0.5    0.     0.125]
 [ 0.125  0.     0.6    0.167  0.     0.2    0.     0.25   0.   ]]
11
[ 0.12306  0.07194  0.06382  0.10603  0.05106  0.12897  0.1237   0.18745
  0.14399]


array([7, 8, 5, 6, 0, 3, 1, 2, 4], dtype=int64)

In [112]:
x = zeros(9)
x[0] = 1
for n in range(500):
    xnew = dot(H,x)
    err = mean(abs(xnew-x))
    if err < 1e-5:
        break
    x = xnew
print(n)
print(around(x,5))
sum(x)

11
[ 0.12306  0.07194  0.06382  0.10603  0.05106  0.12897  0.1237   0.18745
  0.14399]


1.0

In [113]:
flipud(argsort(x))

array([7, 8, 5, 6, 0, 3, 1, 2, 4], dtype=int64)