## Week 5
Chanh Nguyen

In [1]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *

In [6]:
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Problem 1

In [8]:
L = array([1, 0, 0, 1, 1, 0, 1, 5/3, 1]).reshape(3, 3)
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  0.        ],
       [ 1.        ,  1.66666667,  1.        ]])

In [9]:
U = array([1, 2, 4, 0, 3, 21, 0, 0, 0]).reshape(3, 3)
U

array([[ 1,  2,  4],
       [ 0,  3, 21],
       [ 0,  0,  0]])

In [11]:
A = dot(L, U)
A

array([[  1.,   2.,   4.],
       [  1.,   5.,  25.],
       [  1.,   7.,  39.]])

In [12]:
from scipy.linalg import lu, solve

In [17]:
P, Li, Ui = lu(A)
print('-----P is')
print(P)
print('----Li is')
print(Li)
print('-------Ui is')
print(Ui)

-----P is
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
----Li is
[[ 1.   0.   0. ]
 [ 1.   1.   0. ]
 [ 1.   0.6  1. ]]
-------Ui is
[[  1.00000000e+00   2.00000000e+00   4.00000000e+00]
 [  0.00000000e+00   5.00000000e+00   3.50000000e+01]
 [  0.00000000e+00   0.00000000e+00  -3.10862447e-15]]


In [18]:
dot(dot(P, Li), Ui)

array([[  1.,   2.,   4.],
       [  1.,   5.,  25.],
       [  1.,   7.,  39.]])

### Problem 3

In [19]:
A = array([1, 4, 1, 1, 6, -1, 2, -1, 2]).reshape(3, 3)
A

array([[ 1,  4,  1],
       [ 1,  6, -1],
       [ 2, -1,  2]])

In [26]:
b = array([7, 3, 5])
b

array([7, 3, 5])

In [28]:
x = solve(A, b)
x

array([ -3.33066907e-16,   1.00000000e+00,   3.00000000e+00])

### Problem 4

In [30]:
def matInv(a):
    n = len(a[0])
    aInv = identity(n)
    a = LUdecomp(a)
    for i in range(n):
        aInv[:,i] = LUsolve(a, aInv[:,i])
    return aInv

In [31]:
A = array([7, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
A

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])

In [32]:
matInv(A)

NameError: name 'LUdecomp' is not defined

In [36]:
def LUdecomp(a):
    n = len(a)
    for k in range(0, n-1):
        for i in range(k+1,n):
            if a[i, k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a        

In [34]:
def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - dot(a[k,0:k],b[0:k])
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - dot(a[k,k+1:n], b[k+1:n]))/a[k,k]
    return b    

In [37]:
matInv(A)

array([[ 0.14285714, -0.07142857,  0.10714286, -0.28571429],
       [ 0.        ,  0.16666667, -0.08333333,  0.33333333],
       [ 0.        ,  0.        ,  0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.5       ]])

In [40]:
from numpy.linalg import inv

In [41]:
inv(A)

array([[ 0.14285714, -0.07142857,  0.10714286, -0.28571429],
       [ 0.        ,  0.16666667, -0.08333333,  0.33333333],
       [ 0.        ,  0.        ,  0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.5       ]])

In [42]:
A = array([0.6, -0.4, 1.0, -0.3, 0.2, 0.5, 0.6, -1.0, 0.5]).reshape(3, 3)
A

array([[ 0.6, -0.4,  1. ],
       [-0.3,  0.2,  0.5],
       [ 0.6, -1. ,  0.5]])

In [43]:
inv(A)

array([[ 1.66666667, -2.22222222, -1.11111111],
       [ 1.25      , -0.83333333, -1.66666667],
       [ 0.5       ,  1.        ,  0.        ]])

In [57]:
matInv(A)

C:\Users\Chanh Nguyen\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: invalid value encountered in subtract


array([[ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan]])

In [45]:
B = array([2, 4, 3, 0, 6, 5, 0, 0, 2]).reshape(3, 3)
B 

array([[2, 4, 3],
       [0, 6, 5],
       [0, 0, 2]])

In [46]:
inv(B)

array([[ 0.5       , -0.33333333,  0.08333333],
       [ 0.        ,  0.16666667, -0.41666667],
       [ 0.        ,  0.        ,  0.5       ]])

In [47]:
matInv(B)

array([[ 0.5       , -0.33333333,  0.08333333],
       [ 0.        ,  0.16666667, -0.41666667],
       [ 0.        ,  0.        ,  0.5       ]])

In [48]:
B = array([2, 0, 0, 3, 4, 0, 4, 5, 6]).reshape(3, 3)
B

array([[2, 0, 0],
       [3, 4, 0],
       [4, 5, 6]])

In [49]:
inv(B)

array([[  5.00000000e-01,   0.00000000e+00,   1.54074396e-33],
       [ -3.75000000e-01,   2.50000000e-01,  -2.22044605e-17],
       [ -2.08333333e-02,  -2.08333333e-01,   1.66666667e-01]])

In [50]:
matInv(B)

array([[ 0.5       ,  0.        ,  0.        ],
       [-0.25      ,  0.25      ,  0.        ],
       [-0.16666667, -0.16666667,  0.16666667]])

In [54]:
A6 = array([5., -3., -1., 0., -2., 1., 1., 1., 3., -5., 1., 2., 0., 8., -4., -3.]).reshape(4, 4)
A6 

array([[ 5., -3., -1.,  0.],
       [-2.,  1.,  1.,  1.],
       [ 3., -5.,  1.,  2.],
       [ 0.,  8., -4., -3.]])

In [55]:
inv(A6)

array([[  1.12500000e+00,   1.00000000e+00,  -8.75000000e-01,
         -2.50000000e-01],
       [  8.12500000e-01,   1.00000000e+00,  -6.87500000e-01,
         -1.25000000e-01],
       [  2.18750000e+00,   2.00000000e+00,  -2.31250000e+00,
         -8.75000000e-01],
       [ -7.50000000e-01,  -5.55111512e-16,   1.25000000e+00,
          5.00000000e-01]])

In [56]:
matInv(A6)

array([[ 1.125 ,  1.    , -0.875 , -0.25  ],
       [ 0.8125,  1.    , -0.6875, -0.125 ],
       [ 2.1875,  2.    , -2.3125, -0.875 ],
       [-0.75  ,  0.    ,  1.25  ,  0.5   ]])

In [58]:
B6 = array([1., 3., -9., 6., 4., 2., -1., 6., 7., 1., 3., 2., -3., 15., 5., 8., -1., 1., 4., 2., 11., 1., -2., 18., 7.]).reshape(5, 5)
B6 

array([[  1.,   3.,  -9.,   6.,   4.],
       [  2.,  -1.,   6.,   7.,   1.],
       [  3.,   2.,  -3.,  15.,   5.],
       [  8.,  -1.,   1.,   4.,   2.],
       [ 11.,   1.,  -2.,  18.,   7.]])

In [59]:
inv(B6)

array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.33333333e-01,  -3.33333333e-01,   6.66666667e-01,
          3.33333333e-01,  -3.33333333e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])

In [60]:
matInv(B6)

C:\Users\Chanh Nguyen\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\Chanh Nguyen\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: RuntimeWarning: invalid value encountered in multiply
C:\Users\Chanh Nguyen\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: RuntimeWarning: invalid value encountered in double_scalars


array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan]])

## Matrix algebra rules

In [64]:
from numpy.random import randint
A = randint(0, 10, 9).reshape(3, 3)
B = randint(0, 10, 9).reshape(3, 3)
print(A)
B

[[2 6 4]
 [4 2 8]
 [9 4 8]]


array([[2, 1, 5],
       [1, 8, 2],
       [2, 1, 9]])

In [71]:
from scipy.linalg import lu_factor, lu_solve, lu, solve, inv, det

In [66]:
?lu_factor

In [67]:
def matInv(a):
    n = len(a[0])
    aInv = identity(n)
    a = lu_factor(a)
    for i in range(n):
        aInv[:,i] = lu_solve(a, aInv[:,i])
    return aInv

In [68]:
matInv(A)

array([[ -8.00000000e-02,  -1.60000000e-01,   2.00000000e-01],
       [  2.00000000e-01,  -1.00000000e-01,   6.75787928e-18],
       [ -1.00000000e-02,   2.30000000e-01,  -1.00000000e-01]])

In [69]:
A = array([0.6, -0.4, 1.0, -0.3, 0.2, 0.5, 0.6, -1.0, 0.5]).reshape(3, 3)
A

array([[ 0.6, -0.4,  1. ],
       [-0.3,  0.2,  0.5],
       [ 0.6, -1. ,  0.5]])

In [70]:
matInv(A)

array([[ 1.66666667, -2.22222222, -1.11111111],
       [ 1.25      , -0.83333333, -1.66666667],
       [ 0.5       ,  1.        ,  0.        ]])

In [72]:
B6 = array([1., 3., -9., 6., 4., 2., -1., 6., 7., 1., 3., 2., -3., 15., 5., 8., -1., 1., 4., 2., 11., 1., -2., 18., 7.]).reshape(5, 5)
B6

array([[  1.,   3.,  -9.,   6.,   4.],
       [  2.,  -1.,   6.,   7.,   1.],
       [  3.,   2.,  -3.,  15.,   5.],
       [  8.,  -1.,   1.,   4.,   2.],
       [ 11.,   1.,  -2.,  18.,   7.]])

In [73]:
matInv(B6)

array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.33333333e-01,  -3.33333333e-01,   6.66666667e-01,
          3.33333333e-01,  -3.33333333e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])

## Gauss-Seidel method

In [87]:
def gaussSeidel(A, b, x0):
    n = len(x0)
    x = x0
    for k in range(10):
        for i in range(n):
            s = 0
            for j in range(n):
                if j != i:
                    s += A[i,j] * x[j]
            x[i] = 1/A[i,i] * (b[i] - s)
    return x        

In [90]:
A = array([-2.,5,9,7,1,1,-3,7,-1]).reshape(3,3)
A

array([[-2.,  5.,  9.],
       [ 7.,  1.,  1.],
       [-3.,  7., -1.]])

In [91]:
b = array([1.,6,-26])
b

array([  1.,   6., -26.])

In [92]:
x0 = array([1.,1.,1.])

In [93]:
x = gaussSeidel(A,b,x0)
x

array([ -2.69258436e+22,   1.94047436e+23,   1.43910958e+24])

In [94]:
A1 = array([7.,1,1,-3,7,-1,-2,5,9]).reshape(3,3)
b1 = array([6., -26, 0])
